version: '3'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    image: dinesh781204/backend:latest    
    ports:
      - "3002:3000"

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    image: dinesh781204/frontend:latest    
    ports:
      - "8085:80"

  prometheus:
    image: prom/prometheus
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"      
